[INFO] 2024-05-05 16:34:52,835 server.py:72: Edit config: {"server_port":8000,"log_level":"INFO","server_mode":"PROD","parsers_module_path":"aiconfig_model_registry.py","env_file_path":"/Users/daehako/.env"}
[INFO] 2024-05-05 16:34:52,835 server.py:73: Starting server on http://localhost:8000
[INFO] 2024-05-05 16:34:52,835 server_utils.py:298: Initializing server state for 'edit' command
[WARNING] 2024-05-05 16:34:52,835 server_utils.py:280: Failed to load parsers module: File does not exist: /Users/daehako/Desktop/cover-letter/aiconfig_model_registry.py
[INFO] 2024-05-05 16:34:52,835 server.py:99: Initialized server state
[INFO] 2024-05-05 16:34:52,835 server.py:104: Running in ServerMode.PROD mode
[ERROR] 2024-05-09 23:36:48,168 app.py:838: Exception on /api/load_content [POST]
Traceback (most recent call last):
  File "/Users/daehako/Desktop/cover-letter/env/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daehako/Desktop/cover-letter/env/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daehako/Desktop/cover-letter/env/lib/python3.11/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/daehako/Desktop/cover-letter/env/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daehako/Desktop/cover-letter/env/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daehako/Desktop/cover-letter/env/lib/python3.11/site-packages/aiconfig/editor/server/server.py", line 238, in load_content
    aiconfig = AIConfigRuntime.load_yaml(content)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daehako/Desktop/cover-letter/env/lib/python3.11/site-packages/aiconfig/Config.py", line 159, in load_yaml
    return cls.load_json(config_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daehako/Desktop/cover-letter/env/lib/python3.11/site-packages/aiconfig/Config.py", line 143, in load_json
    config_runtime = cls.model_validate_json(config_json)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daehako/Desktop/cover-letter/env/lib/python3.11/site-packages/pydantic/main.py", line 580, in model_validate_json
    return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for AIConfigRuntime
  Input should be an object [type=model_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.7/v/model_type
[INFO] 2024-05-09 23:36:50,964 server.py:72: Edit config: {"server_port":8001,"log_level":"INFO","server_mode":"PROD","parsers_module_path":"aiconfig_model_registry.py","env_file_path":"/Users/daehako/.env"}
[INFO] 2024-05-09 23:36:50,964 server.py:73: Starting server on http://localhost:8001
[INFO] 2024-05-09 23:36:50,965 server_utils.py:298: Initializing server state for 'edit' command
[WARNING] 2024-05-09 23:36:50,965 server_utils.py:280: Failed to load parsers module: File does not exist: /Users/daehako/Desktop/cover-letter/aiconfig_model_registry.py
[INFO] 2024-05-09 23:36:50,965 server.py:99: Initialized server state
[INFO] 2024-05-09 23:36:50,965 server.py:104: Running in ServerMode.PROD mode
[INFO] 2024-05-14 23:47:37,868 server.py:72: Edit config: {"server_port":8080,"aiconfig_path":"my_aiconfig.aiconfig.json","log_level":"INFO","server_mode":"PROD","parsers_module_path":"aiconfig_model_registry.py","env_file_path":null}
[INFO] 2024-05-14 23:47:37,868 server.py:73: Starting server on http://localhost:8080
[INFO] 2024-05-14 23:47:37,868 server.py:79: Opening browser at http://localhost:8080
[INFO] 2024-05-14 23:47:37,968 server_utils.py:298: Initializing server state for 'edit' command
[WARNING] 2024-05-14 23:47:37,968 server_utils.py:280: Failed to load parsers module: File does not exist: /Users/daehako/Desktop/cover-letter/aiconfig_model_registry.py
[WARNING] 2024-05-14 23:47:37,968 server_utils.py:308: No .env file path provided: 'None'
[INFO] 2024-05-14 23:47:37,968 server_utils.py:338: Creating new AIConfig at my_aiconfig.aiconfig.json
[INFO] 2024-05-14 23:47:37,969 server_utils.py:352: Created new AIConfig
[INFO] 2024-05-14 23:47:37,970 server_utils.py:356: Saved new AIConfig to my_aiconfig.aiconfig.json (aiconfig path field: my_aiconfig.aiconfig.json)
[INFO] 2024-05-14 23:47:37,970 server.py:99: Initialized server state
[INFO] 2024-05-14 23:47:37,970 server.py:104: Running in ServerMode.PROD mode
[INFO] 2024-05-14 23:50:09,693 server.py:72: Edit config: {"server_port":8000,"log_level":"INFO","server_mode":"PROD","parsers_module_path":"aiconfig_model_registry.py","env_file_path":"/Users/daehako/.env"}
[INFO] 2024-05-14 23:50:09,693 server.py:73: Starting server on http://localhost:8000
[INFO] 2024-05-14 23:50:09,693 server_utils.py:298: Initializing server state for 'edit' command
[WARNING] 2024-05-14 23:50:09,693 server_utils.py:280: Failed to load parsers module: File does not exist: /Users/daehako/Desktop/cover-letter/aiconfig_model_registry.py
[INFO] 2024-05-14 23:50:09,693 server.py:99: Initialized server state
[INFO] 2024-05-14 23:50:09,693 server.py:104: Running in ServerMode.PROD mode
